# -*- coding: utf-8 -*-
"""
Flask HTTP route compatibility shim.
"""

from app.models import advanced_search, update_user_profile
from app.http.registry import register_routes
from config import (
    DESKTOP_CLIENT_ARTIFACT_SHA256,
    DESKTOP_CLIENT_ARTIFACT_SIGNATURE,
    DESKTOP_CLIENT_CANARY_ARTIFACT_SHA256,
    DESKTOP_CLIENT_CANARY_ARTIFACT_SIGNATURE,
    DESKTOP_CLIENT_CANARY_DOWNLOAD_URL,
    DESKTOP_CLIENT_CANARY_LATEST_VERSION,
    DESKTOP_CLIENT_CANARY_MIN_VERSION,
    DESKTOP_CLIENT_CANARY_RELEASE_NOTES_URL,
    DESKTOP_CLIENT_CANARY_SIGNATURE_ALG,
    DESKTOP_CLIENT_CHANNEL_DEFAULT,
    DESKTOP_CLIENT_DOWNLOAD_URL,
    DESKTOP_CLIENT_LATEST_VERSION,
    DESKTOP_CLIENT_MIN_VERSION,
    DESKTOP_CLIENT_RELEASE_NOTES_URL,
    DESKTOP_CLIENT_SIGNATURE_ALG,
    DESKTOP_ONLY_MODE,
    REQUIRE_SIGNED_UPDATES_IN_PROD,
)

__all__ = [
    "DESKTOP_CLIENT_ARTIFACT_SHA256",
    "DESKTOP_CLIENT_ARTIFACT_SIGNATURE",
    "DESKTOP_CLIENT_CANARY_ARTIFACT_SHA256",
    "DESKTOP_CLIENT_CANARY_ARTIFACT_SIGNATURE",
    "DESKTOP_CLIENT_CANARY_DOWNLOAD_URL",
    "DESKTOP_CLIENT_CANARY_LATEST_VERSION",
    "DESKTOP_CLIENT_CANARY_MIN_VERSION",
    "DESKTOP_CLIENT_CANARY_RELEASE_NOTES_URL",
    "DESKTOP_CLIENT_CANARY_SIGNATURE_ALG",
    "DESKTOP_CLIENT_CHANNEL_DEFAULT",
    "DESKTOP_CLIENT_DOWNLOAD_URL",
    "DESKTOP_CLIENT_LATEST_VERSION",
    "DESKTOP_CLIENT_MIN_VERSION",
    "DESKTOP_CLIENT_RELEASE_NOTES_URL",
    "DESKTOP_CLIENT_SIGNATURE_ALG",
    "DESKTOP_ONLY_MODE",
    "REQUIRE_SIGNED_UPDATES_IN_PROD",
    "advanced_search",
    "register_routes",
    "update_user_profile",
]
